name: Merge Action

on:
  pull_request:
    branches:
      - main
      - devs

jobs:
  merge_from_main:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Main branch merge action
        run: |
          echo "Merged from main branch!"

  merge_from_feature:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Feature branch merge action
        run: |
          echo "Merged from feature branch!"
