name: Merge Action

on:
  push:
    branches:
      - main

jobs:
  log_context:
    runs-on: ubuntu-latest
    steps:
      - name: Log context
        run: |
          echo ${{ github.ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
