name: Merge Action

on:
  push:
    branches:
      - main

  pull_request:
    branchs:
      - main

jobs:
  log_context:
    runs-on: ubuntu-latest
    steps:
      - name: Log context
        run: |
          echo Ref ${{ github.ref }}
          echo Base ref ${{ github.base_ref }}
          echo Head ref ${{ github.head_ref }}
