name: Merge Action

on:
  # push:
  #  branches:
  #    - main

  pull_request:
    branches:
      - main

jobs:
  log_context:
    runs-on: ubuntu-latest
    steps:
      - name: Log context
        run: |
          echo Ref ${{ github.ref }}
          echo Base ref ${{ github.base_ref }}
          echo Head ref ${{ github.head_ref }}

  from_devs_to_main:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'devs'
    runs-on: ubuntu-latest
    steps:
      - name: Print message for merge to main
        run: |
          echo "Merged from feature or dev branch to main!"

  from_feature_to_main:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.base.ref == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Print message for merge to main
        run: |
          echo "Merged from feature or dev branch to main!"
